name: Messages Validation

on:
  push:
  pull_request:


concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true


jobs:
  messages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Validate messages (warn only)
        run: |
          bash scripts/validate_messages.sh || true
